In [1]:
# Imports
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from matplotlib.colors import LinearSegmentedColormap
import matplotlib as mpltlib
from matplotlib.colors import BoundaryNorm, ListedColormap
import math

In [2]:
# Import data and selected proteins list
data_f = pd.read_csv('../data/PLF_Buckley_Female_YFZvsOJA.tsv', sep='\t')
data_m = pd.read_csv('../data/PLF_Buckley_Male_YFZvsOJA.tsv', sep='\t')

data_f = data_f.rename(columns={'p: Old vs Young' : 'p: Aged vs Young'})
data_m = data_m.rename(columns={'p: Old vs Young' : 'p: Aged vs Young'})

In [3]:
d = data_f
d[d['Uniprot_ID'] == 'CO1A1_RAT']

,Uniprot_ID,Domain_Name,Domain_Start,Domain_Finish,p: Aged vs Young,Domain Type,Domain_Length,FZ1_F (ms-status_RAT1),FZ2_F (ms-status_RAT2),FZ3_F (ms-status_RAT3),JA2_F (ms-status_RAT8),JA5_F (ms-status_RAT11),JA6_F (ms-status_RAT12),Diff Young vs old (average young - old / 50),Average Young,Average Old,Peptides contributing to Young,Peptides contributing to Old,Original_FZ1_F (ms-status_RAT1),Original_FZ2_F (ms-status_RAT2),Original_FZ3_F (ms-status_RAT3),Original_JA2_F (ms-status_RAT8),Original_JA5_F (ms-status_RAT11),Original_JA6_F (ms-status_RAT12),GeneAC,Uniprot_ACs
747,CO1A1_RAT,50Step_Domain_p0_to_50,0,50,1.000,50.0 AA STEP,50,0,0,0,0,0,0,0.00,0,0,NaN,NaN,0,0,0,0,0,0,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
748,CO1A1_RAT,50Step_Domain_p50.0_to_100.0,50,100,1.000,50.0 AA STEP,50,1,2,1,1,0,1,0.00,1,1,EDLDCPNPQKR,EDLDCPNPQKR,1,2,1,1,0,1,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
749,CO1A1_RAT,50Step_Domain_p100.0_to_150.0,100,150,1.000,50.0 AA STEP,50,0,0,0,0,0,0,0.00,0,0,NaN,NaN,0,0,0,0,0,0,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
750,CO1A1_RAT,50Step_Domain_p150.0_to_200.0,150,200,1.000,50.0 AA STEP,50,9,12,8,11,13,12,-0.04,10,12,GLPGPPGAPGPQGFQGPPGEPGEPGASGPMGPR SAGVSVPGPMGP...,GLPGPPGAPGPQGFQGPPGEPGEPGASGPMGPR SAGVSVPGPMGP...,8,11,7,11,11,14,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
751,CO1A1_RAT,50Step_Domain_p200.0_to_250.0,200,250,0.015,50.0 AA STEP,50,24,16,7,31,21,23,-0.18,16,25,GLPGPPGAPGPQGFQGPPGEPGEPGASGPMGPR GLPGTAGLPGMK...,GLPGPPGAPGPQGFQGPPGEPGEPGASGPMGPR GLPGTAGLPGMK...,21,15,6,30,18,26,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
752,CO1A1_RAT,50Step_Domain_p250.0_to_300.0,250,300,0.336,50.0 AA STEP,50,26,24,32,30,40,32,-0.14,27,34,GDTGPAGPKGEPGSPGENGAPGQMGPR GEPGSPGENGAPGQMGPR...,GDTGPAGPKGEPGSPGENGAPGQMGPR GEPGSPGENGAPGQMGPR...,22,23,28,29,34,37,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
753,CO1A1_RAT,50Step_Domain_p300.0_to_350.0,300,350,0.111,50.0 AA STEP,50,13,17,17,20,22,28,-0.14,16,23,GNDGAVGAAGPPGPTGPTGPPGFPGAAGAK GNDGAVGAAGPPGPT...,GEAGPQGAR GNDGAVGAAGPPGPTGPTGPPGFPGAAGAK GNDGA...,11,16,15,19,19,32,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
754,CO1A1_RAT,50Step_Domain_p350.0_to_400.0,350,400,1.000,50.0 AA STEP,50,26,39,34,37,30,36,-0.02,33,34,GANGAPGIAGAPGFPGAR GEPGPPGPAGAAGPAGNPGADGQPGAK...,GANGAPGIAGAPGFPGAR GANGAPGIAGAPGFPGARGPSGPQGPS...,22,37,30,36,25,41,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
755,CO1A1_RAT,50Step_Domain_p400.0_to_450.0,400,450,1.000,50.0 AA STEP,50,24,26,30,22,24,22,0.08,27,23,GANGAPGIAGAPGFPGAR GDTGAKGEPGPAGVQGPPGPAGEEGK ...,GANGAPGIAGAPGFPGAR GANGAPGIAGAPGFPGARGPSGPQGPS...,21,25,26,21,20,25,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
756,CO1A1_RAT,50Step_Domain_p450.0_to_500.0,450,500,1.000,50.0 AA STEP,50,24,28,26,27,32,27,-0.06,26,29,GARGEPGPSGLPGPPGER GDTGAKGEPGPAGVQGPPGPAGEEGK ...,GARGEPGPSGLPGPPGER GDTGAKGEPGPAGVQGPPGPAGEEGK ...,21,27,23,26,27,31,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
757,CO1A1_RAT,50Step_Domain_p500.0_to_550.0,500,550,1.000,50.0 AA STEP,50,13,11,13,13,17,14,-0.06,12,15,GLTGSPGSPGPDGK GSPGEAGRPGEAGLPGAK GSPGPAGPKGSP...,GLTGSPGSPGPDGK GLTGSPGSPGPDGKTGPPGPAGQDGRPGPAG...,11,10,11,13,14,16,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
758,CO1A1_RAT,50Step_Domain_p550.0_to_600.0,550,600,1.000,50.0 AA STEP,50,34,30,39,37,41,35,-0.08,34,38,GQAGVMGFPGPK GQAGVMGFPGPKGTAGEPGK GVPGPPGAVGPA...,GLTGSPGSPGPDGKTGPPGPAGQDGRPGPAGPPGAR GQAGVMGFP...,29,28,34,36,35,40,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
759,CO1A1_RAT,50Step_Domain_p600.0_to_650.0,600,650,1.000,50.0 AA STEP,50,10,12,9,11,12,10,-0.02,10,11,DGEAGAQGAPGPAGPAGER GVPGPPGAVGPAGK GVPGPPGAVGP...,DGEAGAQGAPGPAGPAGER GVPGPPGAVGPAGK GVPGPPGAVGP...,9,11,8,11,10,12,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
760,CO1A1_RAT,50Step_Domain_p650.0_to_700.0,650,700,1.000,50.0 AA STEP,50,27,17,22,19,15,17,0.10,22,17,GDTGAPGAPGSQGAPGLQGMPGER GNNGAPGNDGAKGDTGAPGAP...,GDTGAPGAPGSQGAPGLQGMPGER GNNGAPGNDGAKGDTGAPGAP...,23,16,19,18,13,20,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
761,CO1A1_RAT,50Step_Domain_p700.0_to_750.0,700,750,1.000,50.0 AA STEP,50,20,16,17,17,13,18,0.04,18,16,GAAGLPGPK GAAGLPGPKGDR GDTGAPGAPGSQGAPGLQGMPGE...,GAAGLPGPK GAAGLPGPKGDR GADGSPGKDGVR GDTGAPGAPG...,17,15,15,16,11,21,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
762,CO1A1_RAT,50Step_Domain_p750.0_to_800.0,750,800,1.000,50.0 AA STEP,50,30,26,21,27,20,34,-0.02,26,27,GAPGDRGEPGPPGPAGFAGPPGADGQPGAK GEPGPPGPAGFAGPP...,GADGSPGKDGVR GAPGDRGEPGPPGPAGFAGPPGADGQPGAK GE...,26,25,18,26,17,39,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
763,CO1A1_RAT,50Step_Domain_p800.0_to_850.0,800,850,1.000,50.0 AA STEP,50,26,25,25,22,19,22,0.08,25,21,GAPGDRGEPGPPGPAGFAGPPGADGQPGAK GDAGPPGPAGPAGPP...,GAPGDRGEPGPPGPAGFAGPPGADGQPGAK GDAGPPGPAGPAGPP...,22,24,22,21,16,25,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
764,CO1A1_RAT,50Step_Domain_p850.0_to_900.0,850,900,0.075,50.0 AA STEP,50,36,41,46,30,34,35,0.16,41,33,GAAGPPGATGFPGAAGR GDAGPPGPAGPAGPPGPIGNVGAPGPK ...,GAAGPPGATGFPGAAGR GDAGPPGPAGPAGPPGPIGNVGAPGPK ...,31,39,40,29,29,40,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
765,CO1A1_RAT,50Step_Domain_p900.0_to_950.0,900,950,1.000,50.0 AA STEP,50,15,18,19,12,12,15,0.08,17,13,GETGPAGRPGEVGPPGPPGPAGEK GSPGADGPAGSPGTPGPQGIA...,GETGPAGRPGEVGPPGPPGPAGEK GSPGADGPAGSPGTPGPQGIA...,13,17,17,12,10,17,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
766,CO1A1_RAT,50Step_Domain_p950.0_to_1000.0,950,1000,0.000,50.0 AA STEP,50,58,51,61,46,48,41,0.24,57,45,GFPGLPGPSGEPGK GFPGLPGPSGEPGKQGPSGASGER GPPGPM...,GFPGLPGPSGEPGK GFPGLPGPSGEPGKQGPSGASGER GPPGPM...,50,48,53,45,41,47,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
767,CO1A1_RAT,50Step_Domain_p1000.0_to_1050.0,1000,1050,1.000,50.0 AA STEP,50,57,42,48,46,45,45,0.08,49,45,EGSPGAEGSPGRDGAPGAK GDRGETGPAGPPGAPGAPGAPGPVGP...,EGSPGAEGSPGR EGSPGAEGSPGRDGAPGAK GDRGETGPAGPPG...,49,40,42,45,38,52,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
768,CO1A1_RAT,50Step_Domain_p1050.0_to_1100.0,1050,1100,0.015,50.0 AA STEP,50,45,48,50,36,39,40,0.20,48,38,GDRGETGPAGPPGAPGAPGAPGPVGPAGK GETGPAGPAGPIGPAG...,GDRGETGPAGPPGAPGAPGAPGPVGPAGK GETGPAGPAGPIGPAG...,39,46,44,35,33,46,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
769,CO1A1_RAT,50Step_Domain_p1100.0_to_1150.0,1100,1150,1.000,50.0 AA STEP,50,26,30,21,30,27,29,-0.06,26,29,DGLNGLPGPIGPPGPR GFSGLQGPPGSPGSPGEQGPSGASGPAGP...,DGLNGLPGPIGPPGPR GFSGLQGPPGSPGSPGEQGPSGASGPAGP...,22,28,18,29,23,33,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
770,CO1A1_RAT,50Step_Domain_p1150.0_to_1200.0,1150,1200,1.000,50.0 AA STEP,50,12,13,6,12,14,11,-0.04,10,12,DGLNGLPGPIGPPGPR GPPGSAGSPGKDGLNGLPGPIGPPGPR,DGLNGLPGPIGPPGPR GPPGSAGSPGKDGLNGLPGPIGPPGPR,10,12,5,12,12,13,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
771,CO1A1_RAT,50Step_Domain_p1200.0_to_1250.0,1200,1250,1.000,50.0 AA STEP,50,2,3,2,2,4,3,-0.02,2,3,DRDLEVDTTLK SLSQQIENIR,DRDLEVDTTLK SLSQQIENIR SLSQQIENIRSPEGSR,2,3,2,2,3,3,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
772,CO1A1_RAT,50Step_Domain_p1250.0_to_1300.0,1250,1300,1.000,50.0 AA STEP,50,1,1,1,2,2,0,0.00,1,1,NWYISPNPK,NaN,1,1,1,2,2,0,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
773,CO1A1_RAT,50Step_Domain_p1300.0_to_1350.0,1300,1350,1.000,50.0 AA STEP,50,1,1,1,1,0,0,0.02,1,0,NWYISPNPK,NaN,1,1,1,1,0,0,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
774,CO1A1_RAT,50Step_Domain_p1350.0_to_1400.0,1350,1400,1.000,50.0 AA STEP,50,0,2,0,5,2,1,-0.04,1,3,NaN,NSVAYMDQQTGNLKK,0,2,0,5,2,1,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
775,CO1A1_RAT,50Step_Domain_p1400.0_to_1450.0,1400,1450,1.000,50.0 AA STEP,50,0,0,0,2,0,0,-0.02,0,1,NaN,NaN,0,0,0,2,0,0,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r
776,CO1A1_RAT,50Step_Domain_p1450.0_to_1453.0,1450,1453,1.000,50.0 AA STEP,3,0,0,0,0,0,0,0.00,0,0,NaN,NaN,0,0,0,0,0,0,CO1A1_RAT,P02454;\rA3KNA1;\rP02455;\rQ63079;\r

In [4]:
sig = ['APOE', 'APOA1', 'APOA2', 'ALBU', 'FA9', 'FA10', 'MFGM', 'CO1A1', 'CO1A2', 'CO2A1', 'COBA1', 'CO5A1', 'DMP1', 'LUM', 'COMP', 'OSTP', 'FETUA', 'RLA2', 'PRELP', 'SAP', 'CO9', 'H4', 'SERPH', 'NPM', 'SPRC', 'PGCA', 'ANXA5', 'PROS', 'VIME', 'THRB', 'MMP13']

In [5]:
ID = ['Uniprot_ID']
young = ['Original_FZ1_F (ms-status_RAT1)', 'Original_FZ2_F (ms-status_RAT2)', 'Original_FZ3_F (ms-status_RAT3)']
old = ['Original_JA2_F (ms-status_RAT8)', 'Original_JA5_F (ms-status_RAT11)', 'Original_JA6_F (ms-status_RAT12)']

In [6]:
for p in sig:
    data = data_f[data_f['Uniprot_ID'] == p]
    print(p)
    listsample = []
    for index, row in data_f.iterrows():
        isin = 0
        if row['Original_FZ1_F (ms-status_RAT1)'] > 0:
            isin = isin + 1
        if row['Original_FZ2_F (ms-status_RAT2)'] > 0:
            isin = isin + 1
        if row['Original_FZ3_F (ms-status_RAT3)'] > 0:
            isin = isin + 1
        if isin > 1:
            print(isin, 'true')
            listsample.append('true')
        else:
            print(isin, 'false')
            listsample.append('false')
    
    print(len(listsample),listsample.count('true'), listsample.count('false'))

APOE
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
APOA1
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false

1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
APOA2
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false

3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
ALBU
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
FA9
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false

0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
FA10
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
MFGM
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false

0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
CO1A1
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
CO1A2

0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
CO2A1
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false

0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
COBA1
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
CO5A1
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
DMP1

0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
LUM
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
COMP
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false

0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
OSTP
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
FETUA

0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
RLA2
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
PRELP
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true

0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
SAP
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
CO9
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true

3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
H4
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
SERPH
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false

2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
NPM
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
SPRC
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false

3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
PGCA
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
ANXA5
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false

3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
PROS
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
VIME
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true

0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
THRB
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874
MMP13
0 false
0 false
0 false
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
3 true
0 false
2 true
3 true
3 true
3 true
1 false
2 true
2 true
1 false
2 true
2 true
0 false
3 true
3 true
3 true
3 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
2 true
2 true
3 true
2 true
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
1 false
1 false
0 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
3 true
0 false
2 true
2 true
0 false
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
1 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
0 false
2 true
0 false
3 true
0 false
0 false
1 false
1 false
0 false
0 false
0 false
3 true
2 true
0 false
0 false
2 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
2 true
1 false
2 true
1 false
2 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
3 true
1 false
3 true
2 true
3 true
3 true
0 false
2 true
1 false
3 true
2 true
3 true
2 true
0 false
3 true
3 true
3 true
2 true
1 false
1 false
1 false
3 true
0 false
3 true
2 true
1 false
0 false
0 false
3 true
0 false
2 true
2 true
2 true
2 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false

0 false
0 false
0 false
0 false
3 true
1 false
3 true
3 true
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
3 true
2 true
1 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
2 true
1 false
0 false
1 false
1 false
1 false
1 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
1 false
0 false
0 false
2 true
1 false
1 false
3 true
1 false
3 true
3 true
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
2 true
2 true
2 true
2 true
1 false
0 false
2 true
0 false
2 true
0 false
2 true
0 false
1 false
0 false
0 false
3 true
2 true
0 false
1 false
2 true
0 false
2 true
3 true
3 true
0 false
1 false
1 false
0 false
2 true
1 false
0 false
0 false
3 true
3 true
2 true
2 true
1 false
1 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
2 true
1 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
2 true
0 false
0 false
0 false
3 true
3 true
2 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
0 false
0 false
2 true
1 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
1 false
0 false
2 true
2 true
0 false
3 true
0 false
0 false
0 false
2 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
1 false
0 false
0 false
1 false
3 true
0 false
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
0 false
0 false
0 false
2 true
1 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
2 true
1 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
2 true
3 true
3 true
2 true
0 false
3 true
0 false
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
2 true
0 false
0 false
1 false
2 true
3 true
3 true
2 true
3 true
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
3 true
0 false
0 false
3 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
0 false
0 false
0 false
3 true
2 true
2 true
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
1 false
0 false
0 false
0 false
0 false
2 true
3 true
1 false
3 true
3 true
3 true
0 false
0 false
0 false
0 false
0 false
1 false
3 true
0 false
0 false
0 false
1 false
1 false
1 false
0 false
0 false
0 false
2 true
3 true
2 true
2 true
0 false
1 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
3 true
2 true
0 false
2 true
0 false
0 false
0 false
3 true
0 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
3 true
0 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
1 false
1 false
1 false
1 false
2 true
2 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
0 false
3 true
0 false
0 false
3 true
1 false
2 true
3 true
2 true
0 false
0 false
3 true
3 true
3 true
3 true
3 true
3 true
1 false
0 false
3 true
3 true
3 true
2 true
3 true
3 true
3 true
3 true
3 true
0 false
3 true
3 true
0 false
2 true
0 false
0 false
0 false
0 false
0 false
1 false
0 false
0 false
1 false
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
2 true
2 true
1 false
0 false
0 false
0 false
0 false
0 false
1 false
0 false
3 true
0 false
0 false
3 true
3 true
0 false
2 true
2 true
3 true
0 false
0 false
3 true
2 true
3 true
2 true
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
3 true
3 true
3 true
3 true
1 false
0 false
0 false
2 true
2 true
0 false
0 false
0 false
0 false
0 false
2 true
0 false
0 false
0 false
0 false
0 false
0 false
0 false
0 false
1174 300 874

In [7]:
data_f.columns

Index(['Uniprot_ID', 'Domain_Name', 'Domain_Start', 'Domain_Finish',
       'p: Aged vs Young', 'Domain Type', 'Domain_Length',
       'FZ1_F (ms-status_RAT1)', 'FZ2_F (ms-status_RAT2)',
       'FZ3_F (ms-status_RAT3)', 'JA2_F (ms-status_RAT8)',
       'JA5_F (ms-status_RAT11)', 'JA6_F (ms-status_RAT12)',
       'Diff Young vs old (average young - old / 50)', 'Average Young',
       'Average Old', 'Peptides contributing to Young',
       'Peptides contributing to Old', 'Original_FZ1_F (ms-status_RAT1)',
       'Original_FZ2_F (ms-status_RAT2)', 'Original_FZ3_F (ms-status_RAT3)',
       'Original_JA2_F (ms-status_RAT8)', 'Original_JA5_F (ms-status_RAT11)',
       'Original_JA6_F (ms-status_RAT12)', 'GeneAC', 'Uniprot_ACs'],
      dtype='object')

In [8]:
FemaleSampleNames = ['Original_FZ1_F (ms-status_RAT1)', 'Original_FZ2_F (ms-status_RAT2)', 'Original_FZ3_F (ms-status_RAT3)',
       'Original_JA2_F (ms-status_RAT8)', 'Original_JA5_F (ms-status_RAT11)',
       'Original_JA6_F (ms-status_RAT12)']
MaleSampleNames = ['Original_FZ4_M (ms-status_RAT4)',
       'Original_FZ5_M (ms-status_RAT5)', 'Original_FZ6_M (ms-status_RAT6)',
       'Original_JA1_M (ms-status_RAT7)', 'Original_JA3_M (ms-status_RAT9)', 'Original_JA4_M (ms-status_RAT10)']

ProtList = ['CO1A1_RAT', 'CO1A2_RAT', 'CO2A1_RAT', 'OSTP_RAT', 'THRB_RAT', 'APOE_RAT', 'COMP_RAT']
datasets = [data_f, data_m]
def checkproteinpresence(dataset, samples):
    for p in ProtList:
        d = dataset[dataset['Uniprot_ID'] == p]
        notpresent = (d[samples] == 0).all()
        print(p, notpresent)

In [9]:
checkproteinpresence(data_f, FemaleSampleNames)

CO1A1_RAT Original_FZ1_F (ms-status_RAT1)     False
Original_FZ2_F (ms-status_RAT2)     False
Original_FZ3_F (ms-status_RAT3)     False
Original_JA2_F (ms-status_RAT8)     False
Original_JA5_F (ms-status_RAT11)    False
Original_JA6_F (ms-status_RAT12)    False
dtype: bool
CO1A2_RAT Original_FZ1_F (ms-status_RAT1)     False
Original_FZ2_F (ms-status_RAT2)     False
Original_FZ3_F (ms-status_RAT3)     False
Original_JA2_F (ms-status_RAT8)     False
Original_JA5_F (ms-status_RAT11)    False
Original_JA6_F (ms-status_RAT12)    False
dtype: bool
CO2A1_RAT Original_FZ1_F (ms-status_RAT1)     False
Original_FZ2_F (ms-status_RAT2)     False
Original_FZ3_F (ms-status_RAT3)     False
Original_JA2_F (ms-status_RAT8)     False
Original_JA5_F (ms-status_RAT11)    False
Original_JA6_F (ms-status_RAT12)    False
dtype: bool
OSTP_RAT Original_FZ1_F (ms-status_RAT1)     False
Original_FZ2_F (ms-status_RAT2)     False
Original_FZ3_F (ms-status_RAT3)     False
Original_JA2_F (ms-status_RAT8)     False
Original_JA5_F (ms-status_RAT11)    False
Original_JA6_F (ms-status_RAT12)    False
dtype: bool
THRB_RAT Original_FZ1_F (ms-status_RAT1)     False
Original_FZ2_F (ms-status_RAT2)     False
Original_FZ3_F (ms-status_RAT3)     False
Original_JA2_F (ms-status_RAT8)     False
Original_JA5_F (ms-status_RAT11)    False
Original_JA6_F (ms-status_RAT12)    False
dtype: bool
APOE_RAT Original_FZ1_F (ms-status_RAT1)     False
Original_FZ2_F (ms-status_RAT2)     False
Original_FZ3_F (ms-status_RAT3)     False
Original_JA2_F (ms-status_RAT8)     False
Original_JA5_F (ms-status_RAT11)    False
Original_JA6_F (ms-status_RAT12)    False
dtype: bool
COMP_RAT Original_FZ1_F (ms-status_RAT1)     False
Original_FZ2_F (ms-status_RAT2)     False
Original_FZ3_F (ms-status_RAT3)     False
Original_JA2_F (ms-status_RAT8)     False
Original_JA5_F (ms-status_RAT11)    False
Original_JA6_F (ms-status_RAT12)    False
dtype: bool

In [10]:
checkproteinpresence(data_m, MaleSampleNames)

CO1A1_RAT Original_FZ4_M (ms-status_RAT4)     True
Original_FZ5_M (ms-status_RAT5)     True
Original_FZ6_M (ms-status_RAT6)     True
Original_JA1_M (ms-status_RAT7)     True
Original_JA3_M (ms-status_RAT9)     True
Original_JA4_M (ms-status_RAT10)    True
dtype: bool
CO1A2_RAT Original_FZ4_M (ms-status_RAT4)     False
Original_FZ5_M (ms-status_RAT5)     False
Original_FZ6_M (ms-status_RAT6)     False
Original_JA1_M (ms-status_RAT7)     False
Original_JA3_M (ms-status_RAT9)     False
Original_JA4_M (ms-status_RAT10)    False
dtype: bool
CO2A1_RAT Original_FZ4_M (ms-status_RAT4)     False
Original_FZ5_M (ms-status_RAT5)     False
Original_FZ6_M (ms-status_RAT6)     False
Original_JA1_M (ms-status_RAT7)     False
Original_JA3_M (ms-status_RAT9)     False
Original_JA4_M (ms-status_RAT10)    False
dtype: bool
OSTP_RAT Original_FZ4_M (ms-status_RAT4)     False
Original_FZ5_M (ms-status_RAT5)     False
Original_FZ6_M (ms-status_RAT6)     False
Original_JA1_M (ms-status_RAT7)     False
Original_JA3_M (ms-status_RAT9)     False
Original_JA4_M (ms-status_RAT10)    False
dtype: bool
THRB_RAT Original_FZ4_M (ms-status_RAT4)     True
Original_FZ5_M (ms-status_RAT5)     True
Original_FZ6_M (ms-status_RAT6)     True
Original_JA1_M (ms-status_RAT7)     True
Original_JA3_M (ms-status_RAT9)     True
Original_JA4_M (ms-status_RAT10)    True
dtype: bool
APOE_RAT Original_FZ4_M (ms-status_RAT4)     False
Original_FZ5_M (ms-status_RAT5)     False
Original_FZ6_M (ms-status_RAT6)     False
Original_JA1_M (ms-status_RAT7)     False
Original_JA3_M (ms-status_RAT9)     False
Original_JA4_M (ms-status_RAT10)    False
dtype: bool
COMP_RAT Original_FZ4_M (ms-status_RAT4)     False
Original_FZ5_M (ms-status_RAT5)     False
Original_FZ6_M (ms-status_RAT6)     False
Original_JA1_M (ms-status_RAT7)     False
Original_JA3_M (ms-status_RAT9)     False
Original_JA4_M (ms-status_RAT10)    False
dtype: bool

In [33]:
# Pivot tables for protein presence
f_filt_det = data_f[data_f['Uniprot_ID'].isin(ProtList)]
f_filt_det = f_filt_det.groupby('Uniprot_ID')[FemaleSampleNames].sum()
f_filt_det['Total'] = f_filt_det.apply(np.sum, axis=1)
f_filt_det.loc['Total'] = f_filt_det.apply(np.sum, axis=0)

f_filt_det

,Original_FZ1_F (ms-status_RAT1),Original_FZ2_F (ms-status_RAT2),Original_FZ3_F (ms-status_RAT3),Original_JA2_F (ms-status_RAT8),Original_JA5_F (ms-status_RAT11),Original_JA6_F (ms-status_RAT12),Total
Uniprot_ID,,,,,,,
APOE_RAT,13,31,14,29,37,30,154
CO1A1_RAT,482,522,486,533,463,632,3118
CO1A2_RAT,199,261,194,339,315,411,1719
CO2A1_RAT,149,192,121,101,113,114,790
COMP_RAT,21,27,9,12,5,8,82
OSTP_RAT,20,48,35,4,12,12,131
THRB_RAT,11,18,20,41,39,34,163
Total,895,1099,879,1059,984,1241,6157

In [35]:
m_filt_det = data_m[data_m['Uniprot_ID'].isin(ProtList)]
m_filt_det = m_filt_det.groupby('Uniprot_ID')[MaleSampleNames].sum()
m_filt_det['total'] = m_filt_det.apply(np.sum, axis=1)
m_filt_det.loc['Total'] = m_filt_det.apply(np.sum, axis=0)

m_filt_det

,Original_FZ4_M (ms-status_RAT4),Original_FZ5_M (ms-status_RAT5),Original_FZ6_M (ms-status_RAT6),Original_JA1_M (ms-status_RAT7),Original_JA3_M (ms-status_RAT9),Original_JA4_M (ms-status_RAT10),total
Uniprot_ID,,,,,,,
APOE_RAT,23,19,23,36,29,37,167
CO1A2_RAT,191,160,203,262,339,315,1470
CO2A1_RAT,147,94,178,95,101,113,728
COMP_RAT,12,3,15,6,12,5,53
OSTP_RAT,46,12,61,8,4,12,143
Total,419,288,480,407,485,482,2561